version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python --version
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - pip install pytest
  build:
    commands:
      - sam --version
      - sam build
      - PYTHONPATH=. pytest -q
artifacts:
  files:
    - .aws-sam/**/*
    - template.yaml
    - buildspec.yaml