AWSTemplateFormatVersion: '2010-09-09'
Description: "demo: CodeCommit + CodeBuild for SAM build/test"

Parameters:
  RepoName:
    Type: String
    Default: demo-aws-build
  BranchName:
    Type: String
    Default: main
  ProjectName:
    Type: String
    Default: demo-aws-build-CodeBuild

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  Repo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: "SAM demo repo"
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildBasicPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              # S3 artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub "${ArtifactBucket.Arn}/*"
              # CodeCommit read
              - Effect: Allow
                Action:
                  - codecommit:GitPull
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetRepository
                Resource: !GetAtt Repo.Arn
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Packaging: ZIP
        Name: !Sub "${ProjectName}.zip"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: false
      Source:
        Type: CODECOMMIT
        Location: !GetAtt Repo.CloneUrlHttp
        BuildSpec: buildspec.yaml
      SourceVersion: !Ref BranchName
      TimeoutInMinutes: 15

Outputs:
  CodeCommitCloneUrlHttp:
    Value: !GetAtt Repo.CloneUrlHttp
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
  CodeBuildProjectName:
    Value: !Ref BuildProject

